---
title: "MN Spatial Dashboard"
author: "SriHarshitha Anuganti"
format: html
editor: visual
embed-resources: true
---
```{r setup, include=FALSE}
#loading libraries
library(dplyr)
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(ggridges)
library(plotly)
library(gtExtras)
library(sf)
library(ggmap)
library(tidycensus)
library(leaflet)
library(osmdata)
library(tigris)
library(ggthemes)
library(viridis)
```

## 1.3 'ggplotly' of Hennepin County using sf, ggmap, tidycensus, ggplot, and plotly
```{r include = FALSE, echo = FALSE, warning=FALSE}
#From OSM
hennepin.box <- osmdata::getbb("hennepin")

#Get the base map (foundational layer)
hennepin.base.map <- get_map(location = hennepin.box,
                             source = "stamen",
                             maptype = "watercolor",
                             crop = TRUE)

census_api_key("CENSUS_API_KEY", 
               overwrite = TRUE,
               install = TRUE)

mn_age_df <- get_acs(
  geography = "tract",
  variables = "B01002_001E", #Code for MEDIAN AGE BYB SEX
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE
)

# Plot normally
age_gg <- ggplot() + 
  geom_sf(data = mn_age_df, aes(fill = estimate)) + 
  labs(title = "Hennepin County 2020 Estimated Age by Zipcode") + 
  theme_void() + 
  scale_fill_viridis_c("Estimated Age by Zipcode, 2020")
```
```{r echo=FALSE}
# Display
age_gg

```

